### ISSUE TITLE
Now Value

### ISSUE THREAD

**Issue by HuwCampbell** [ambiata/icicle#110]
Expressions should be able to compare dates (either the date or the date value) to the snapshot or chord date.

**Comment by HuwCampbell** [comment]
Some operations around Dates would be nice as well, difference, day of week...

**Comment by amosr** [comment]
do you want to think about the fundamental date operations we need?

also, at the moment we can say "windowed 1 month" in Source, but that gets converted to "Window 30 days" in Core. Core Window just takes an Int for the days, but that should probably be changed to a WindowUnit.

Do you want to:
* bring out WindowUnit from Source to a Common module
* change Core Window to use WindowUnit
* change Core evaluators to suit
* change Avalanche conversion

?

**Comment by HuwCampbell** [comment]
I think this is covered off now.
