### ISSUE TITLE
Rebinding inbuilt feature names

### ISSUE THREAD

**Issue by HuwCampbell** [ambiata/icicle#118]
Just a thought really.
Because we have 'fields', 'date', and 'now' taken, it might be nice to have a dictionary option to rebind them.

**Comment by tranma** [comment]
yeah, they aren't keywords, but are somehow special snowflakes anyway....

**Comment by amosr** [comment]
yeah - I also bind ``value`` for non-struct fields, and I was originally thinking of binding ``first`` and ``second`` etc for tuples.

yep, there's definitely a better way, dictionary option sounds reasonable

**Comment by amosr** [comment]
I'm dithering on this - more options are just more ways to write the wrong program..

**Comment by tranma** [comment]
@amosr advocating for police state compiler!

**Comment by amosr** [comment]
the dictionary inheritance is my main concern: if you re-bound the fields in the top dictionary then import another one, and it uses the different field names, it sounds potentially confusing

**Comment by tranma** [comment]
names are hard

**Comment by amosr** [comment]
let's use de bruijns

**Comment by tranma** [comment]
hi there fellow cyclon

**Comment by amosr** [comment]
if we added "date", "now" and "tombstone" as keywords, we could mention them in function definitions. that would probably be useful for a bunch of things, such as ``numflips``.

**Comment by amosr** [comment]
no options for you
