### ISSUE TITLE
Avalanche.Flatten causes code explosion

### ISSUE THREAD

**Issue by amosr** [ambiata/icicle#140]
Flatten duplicates a lot of code.
This should be easily fixed.

```
let x = Bool_fold a b c;
stmts;
```
actually becomes
```
if c {
 let x = a;
 stmts;
} else {
 let x = b;
 stmts;
}
```

however we should introduce a mutable variable instead:
```
alloc x$acc = <default>;
if c {
  write x$acc = a;
} else {
  write x$acc = b;
}
read x = x$acc;
stmts;
```

The same is true of other folds.

**Comment by tranma** [comment]
agree completely. No target compiler will do this lifting-out-of-conditional transformation.

**Comment by jystic** [comment]
:potable_water:

**Comment by amosr** [comment]
@HuwCampbell do you want to take a look at this?

I think you'll only need to modify ``Icicle.Avalanche.Statement.Flatten``, and the important part is actually ``flatFold`` which converts a primitive fold over various types to ifs and stuff.

I believe the array and map and loopy folds are already decent, but the Bool, Option and Sum need some love.

It's a pretty weird transform - it's like it has to do everything inside out to build up the loop nest in the right way, while changing the primitive types. There must be a simpler way to do it, but I didn't find it.

So in
```
  flatFold Core.PrimFoldBool _ [then_, else_, pred]
   = flatX' pred
   $ \pred'
   -> If pred'
        <$> flatX' then_ stm
        <*> flatX' else_ stm
```

Here, ``flatX' :: Exp Core -> (Exp Flat -> FlatM (Statement Flat)) -> …``
That is, it takes an expression with Core primitives, converts it to a flattened primitives, then passes that to the callback.
In this case ``stm`` is the "rest of the computation", like what happens with the result of the Bool fold.

I guess we want something like
```
  flatFold Core.PrimFoldBool _ [then_, else_, pred]
    -- Convert all the arguments. Sorry, this is weird
   = flatX' pred
    $ \pred'
    -> flatX' then_
     $ \then_'
    -> flatX' else_
     $ \else_'
    -> do -- Fresh name for accumulator and result.
            -- We can use same name for acc & result variables because accumulators and variables are in different scopes
           acc <- fresh
           -- Compute the rest of the computation, assuming we've stored result in variable named acc
           stm' <- stm (xVar acc)
           -- Perform if and write result
           let if_ =  If pred' (Write acc … then_)
                                    (Write acc … else_)
           -- After if, read back result from accumulator and then go do the rest of the statements
           let read_ = Read acc acc … stm'
           return (InitAccumulator (Accumulator acc … defaultOfType …) (if_ <> read_))
```

That's the rough idea. I hope I don't appear to be condescending by going into so much detail. I have no doubt that you would figure it out, but this is just a particularly gnarly transform

**Comment by HuwCampbell** [comment]
Sure

**Comment by HuwCampbell** [comment]
Done
