### ISSUE TITLE
Filter of Possibly is wrong

### ISSUE THREAD

**Issue by amosr** [ambiata/icicle#143]
At the moment, if you have an input like ``value :: Element Possibly Bool`` and one of the values is tombstone, then it will be filtered out:
```
filter value ~> blah
```
actually becomes
```
filter (value == Right True) ~> blah
```
but really, it should be something like
```
filter (value == Right True || isLeft value)
~> if    isLeft value
   then ??
   else blah
```

actually in this case, if it is tombstone, we could just say
```
filter (value == Right True || isLeft value) ~> blah
```
because if the filter predicate is tombstone, it will bubble up if it is used in the rest "blah".

**Comment by amosr** [comment]
This is fixed; I just made it treat errors as true predicates.

**Comment by amosr** [comment]
The beautiful thing about treating errors as true predicates is that any error in the predicate will bubble up if the same error (ie tombstone) is used in the body...

**Comment by amosr** [comment]
Reopen

**Comment by amosr** [comment]
This makes count do funny things. If you want to count the number of values larger than 50..
```
filter value > 50 ~> count
```
This actually lets the tombstones/errors through as well, but they aren't forced by the count, just counted.

We can define a different version of count that forces evaluation of some element:
```
# hack for forcing a;
# (case a | _ -> b end) doesn't work because desugars to nothing
seq a b = case a==a | True -> b | False -> b end.

count' v = let fold c = 0 : seq v c + 1 ~> c.
```

**Comment by amosr** [comment]
Must modify desugar to allow saner seq

**Comment by tranma** [comment]
how do you modify desugar (actually, the simplification after desugar...) to allow seq?

**Comment by amosr** [comment]
maybe leave ``case x | _ -> y end`` as a single-arm case, so that ReifyPossibility can convert it to ``case x | Left err -> err | Right _ -> y end`` , if x is possibility.
then probably change ToCore to actually do the simplification current desugar is doing it.
ehhh

**Comment by tranma** [comment]
that feels a bit uncomfortable... but I suppose having some force/seq primitive is a bit overkill, hm.

**Comment by amosr** [comment]
not sure. seems weird to have a seq primitive when we can write one. if you can think of a better way, let me know

**Comment by amosr** [comment]
@HuwCampbell is working on a seq primitive, so this is actually ok.

**Comment by HuwCampbell** [comment]
I've merged in a Seq primitive to Source. Closing.
