### ISSUE TITLE
group into maxby not working?

### ISSUE THREAD

**Issue by amosr** [ambiata/icicle#152]
```
feature injury ~> group date ~> maxby severity location
```

this gives

```
- Core type error:
Reduce error:
    Worker function type error:
        Variable not bound: reify$17$conv$43
```

this also gives error
```
feature injury ~> group 1 ~> maxby 1 1

- Core type error:
Reduce error:
    Worker function type error:
        Variable not bound: reify$3$conv$22
```

and looking at reified (:set +inlined), reify$3 is only mentioned as an error..
```
~> case s$reify$2
     | (Left reify$3) -> Left reify$3
     | (Right reify$4) -> …
```
which should be a postcomputation since it's an aggregate, but looks like it's being put in a reduction somewhere

**Comment by amosr** [comment]
I'll probably look at this tomorrow

**Comment by tranma** [comment]
I have a sinking feeling this is a fresh name problem again

**Comment by amosr** [comment]
maybe, I thought it might have been an issue with that pullLets thing in ToCore.ToCore Case, pulling out the postcomputation bindings inside the scope of the case alternative

**Comment by tranma** [comment]
ah, you mean the pullPosts thing?

**Comment by amosr** [comment]
that's the one. forgot what I called it

**Comment by tranma** [comment]
yeh, it's weird. You don't `pullPosts` if `convertFold` is the one dealing with `Case`, so it shouldn't matter in this scenario. Ah well, we'll see

**Comment by amosr** [comment]
ah you're right

**Comment by amosr** [comment]
I got a smaller one
```
feature salary ~> group 1 ~> case (0,sum value) | (z,s) -> s end
```

**Comment by amosr** [comment]
this was caused by me introducing incorrect annotations in ReifyPossibility.
it created something like
```
case XX@{Aggregate Possibly (SumT Error t)}
 | Left e -> Left@{Aggregate Possibly (SumT Error r)} e@{Error}
 | Right … 
end
```
where the reference to ``e`` didn't have the Aggregate temporality, so the conversion to Core thought it could be lifted to a precomputation, moving it outside of the binding for ``e``.

**Comment by tranma** [comment]
I'm a bit sad about how Temporality is rolled into the same Type soup as everything else... :crying_cat_face:

**Comment by amosr** [comment]
yeh.
as am I, but splitting it up would complicate the already complicated typechecker; you'd need three contexts instead of one, three substitution and unification functions, and so on.
in any case, this seemed like the simplest option

**Comment by tranma** [comment]
yeah, I understand the motivation completely, but it does cause quite a few problems as we (me) forget to deal with temporalities as an edge case in many things. It's not a priority to change it though.
