### ISSUE TITLE
Better well-typed Core generator

### ISSUE THREAD

**Issue by amosr** [ambiata/icicle#155]
It turns out the generator for well-typed Core is most likely to just return constants rather than using the input stream at all.
At the moment we have
```
tryExpForType :: ValType -> Context -> Gen (Exp ..)
```
which takes a context and a type, and tries to build an expression that fits that type. The problem is that it's quite unlikely that any of the variables in the context will have the exact right type.

We should be able to implement the other direction, which returns a (probably) well-typed expression and its type.
```
tryExpWithType :: Context -> Gen (Exp .., ValType)
```
This will be far more likely to choose something from the context. It will probably need to use ``tryExpForType`` when applying primitives and so on though.

**Comment by tranma** [comment]
very useful :potable_water:
