### ISSUE TITLE
Latest/Buf should not be mentioned in LoadResumable/SaveResumable

### ISSUE THREAD

**Issue by amosr** [ambiata/icicle#173]
if you have
```
feature salary ~> latest 5 ~> value
```
this becomes Avalanche something like
```
buf : Buf Int = Buf 5 [];
load_resumable buf;
for facts in facts {
 buf = push buf fact;
}
save_resumable buf;
output (read buf);
```
I think at the moment the ``Buf Int`` gets a ``load_resumable buf`` and whatever. But it should actually not use resumable.
Instead, we actually need another loop afterwards, as well as a buffer of the ids of facts...

```
buf : Buf Int = Buf 5 [];
for facts in facts {
 buf = push buf fact;
}
let buf_ids = read_buf_ids buf;
foreach id in buf_ids {
 keep_fact_in_history id;
}
output (read buf);
```

This really has the same semantics, but instead of storing the result of the latest 5 values as bubblegum, it marks particular facts as being required to recompute. This makes it easier when dealing with new facts being added in the middle of latest facts.

**Comment by amosr** [comment]
This is not necessary for v1 as bubblegum is not used yet

**Comment by amosr** [comment]
thinking about how to make bufs work for history bubblegum in Core evaluator.
I think I'll have to modify the Common Expression evaluator, so I can thread through an extra state that inserts the flavour into a global map ?? or maybe have buf_push take the flavour as an argument, and annotate the buffer values with flavours.

**Comment by tranma** [comment]
> thread through an extra state that inserts the flavour into a global map

such savage!

I think annotate the buffer values with flavours sounds good.

**Comment by amosr** [comment]
I think you're right.
thinking these changes are necessary for Core:

1. add a new "FlavourT" type
2. Core should bind "current flavour" as it does for current fact
3. window and latest push should take flavour
4. VBuf should have [(Flavour,Value)] instead of [Value]
5. after evaluating all the Streams, the Core evaluator looks through heap for VBufs, sucks the flavours out
6. while evaluating all the streams, we concatenate the flavours of the windows
7. after evaluating all streams, all stream folds that are not inside windows, and not latests, are resumables

I'm a little unsure about the last point, because I fear we can have stream folds that produce eg a pair with a resumable and a latest inside it:
```
group key ~> (sum value, latest 5 ~> value)
```
I think this is currently valid, but computing the bubblegum is hard because the "sum value" would have to be the sum at the first latest.

maybe for now we can just focus on latests and windowed bubblegums, and not worry about resumables since we can't really implement them totally for ivory.

**Comment by amosr** [comment]
this is no longer relevant, because we are limiting "resumable queries" to only contain latests and windows. Ice, which reads all data at once, will still support all queries, but Blizzard will only allow latests and windows.
