### ISSUE TITLE
Ensure no array_sum/array_zip in simplified Avalanche

### ISSUE THREAD

**Issue by tranma** [ambiata/icicle#193]
`melt` splits arrays of sums and pairs with into multiple arrays and subst the original array with `sum`/`zip` . In `constructor` we should get rid of all these...*if* the rewrite rules work.
We should check this is the case, so we don't have to handle `sum`/`zip` in toSea ever.

**Comment by amosr** [comment]
good plan. perhaps ideally we'd have a new primitive set for melted?

**Comment by tranma** [comment]
that would be best, if there is time after v1 we should definitely do that.

**Comment by tranma** [comment]
this stuff is gone
