### ISSUE TITLE
Icicle REPL

### ISSUE THREAD

**Issue by tranma** [ambiata/icicle#25]
A REPL for the surface language would be nice. It should output Core and Avalanche, and perhaps interpret it.

More helpful error messages would be nice too, but that's not really in the scope of this issue.

**Comment by amosr** [comment]
so, I think it's worth looking at ``main/icicle.hs`` and ``src/Icicle/Repl.hs``. I'm imagining a conversation would go something like

```
> :load data/example/demographics.psv
ok, 30 rows
> :set show Type
ok
> :set show Core
ok
> :set show Eval
ok
> feature salary ~> sum value
Type: Int

Core:
 Program
   Stream
     s = Source
   Reduce
    f = Fold (+) 0 s
   Returns
    f

Eval:
  homer 1645834
  marge  0
```

**Comment by amosr** [comment]
tran did this ages ago!
