### ISSUE TITLE
Doliverator for multicore

### ISSUE THREAD

**Issue by amosr** [ambiata/icicle#262]
Jacob and I are talking about multicore.
Instead of having the Ice program find the middle of the input, we think a better way is for a single C program to take 1 input and N output pipes, and "dole" work across them for single entity at a time.
So given

```
ABC|stuff|1
ABC|bananas
DEF|bogo
GHI|mongo
GHI|gmono
JKL|bingo
```
then if you ran

```
doliverator A B
```
it would produce something like

```
A:
ABC|stuff|1
ABC|bananas
GHI|mongo
GHI|gmono

B:
DEF|bogo
JKL|bingo
```
and then read and merge the inputs or something.

**Comment by tranma** [comment]
there are two problems

1. it's not general to "merge" the output of these N pipes, e.g if the pipes are all doing "sum value", merging is easy. If they are doing "sd value", not so much.
2. work scheduling is probably not as efficient as splitting the file and let the pipes "go"

**Comment by amosr** [comment]
I had had a few beers when I wrote this, so it's not explained very well.

merging the output is just catting them together, maybe some reordering. the "doliverator" just partitions by entity, so it'll take all of one entity and send it to output 1, then take all of the next entity and send it to output 2. that way there is no actual computation that needs to be shared between the two.

yeah, work scheduling isn't great, but:
1. program currently takes a pipe (output of sort), so we can't split on the file easily
2. since we're only looking at the first line and passing it on, this program should really be able to get at least 800mb/s (based off what ice-bench gets if none of the desired attributes are in the file, so it doesn't need to parse the json or execute)

**Comment by tranma** [comment]
is the input to "doliverator" already grouped by entity or does the doliverator do it?

**Comment by amosr** [comment]
This is done/implemented differently and awesome
