### ISSUE TITLE
Check that input data is indeed sorted

### ISSUE THREAD

**Issue by jystic** [ambiata/icicle#265]
After parsing we should check that the input is sorted by entity/date.

In actual fact we only need dates to be sorted for an entity/attribute pair, perhaps we could store the last date we saw for a given attribute, for the current entity, and check the date we just read against that.

We already have some of this information in the form of the `new_date` array in each program state, unfortunately this is emptied whenever we reach the `psv_max_row_count`.

Multiple values for an entity/attribute/date triple are also not allowed, it would be good to detect this also and error out.

**Comment by amosr** [comment]
This is done
