### ISSUE TITLE
convert array and buf values to explicit construct/push/write calls

### ISSUE THREAD

**Issue by amosr** [ambiata/icicle#280]
at the moment the Sea gen prints array and buf values as chained calls to make, push, write etc. this isn't ideal because a-normalisation doesn't get to pull these out as explicit values.

we should have another step in simp flatten before a-normal that converts values of bufs to explicit push calls

**Comment by jystic** [comment]
Be sure to re-enable the disabled test in the ice cli test (sortings/dictionary.toml) once this is fixed

**Comment by amosr** [comment]
tran fixed!
