### ISSUE TITLE
Segfault when running prop_psv

### ISSUE THREAD

**Issue by jystic** [ambiata/icicle#287]
Just writing down that I saw this happen on Travis:

```
=== prop_psv from test/Icicle/Test/Sea/Psv.hs:51 ===
Test suite test: FAIL
```

Which likely means that it segfaulted, we really need that crazy forking machinery or a signal handler to make this better.

**Comment by amosr** [comment]
I wonder if it could be the date parsing thing I ran into for merge, where the data was something like "|\n" and it found the \n and looked back 20 chars for a pipe

**Comment by jystic** [comment]
hmm, the psv test is only generating valid data at the moment though :(

**Comment by tranma** [comment]
saw this again in https://travis-ci.org/ambiata/icicle/builds/102267649

I've never seen this locally, or on jenkins though. Not sure if it's platform-related

**Comment by tranma** [comment]
I'm looking at this, looks like a good old null pointer :)

```
* thread #1: tid = 0xe457b, 0x000000010cc341f4 jetski.dylib`iarray_ibool_index(x=0x0000000000000000, ix=1) + 20 at type definitions:1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x10)
  * frame #0: 0x000000010cc341f4 jetski.dylib`iarray_ibool_index(x=0x0000000000000000, ix=1) + 20 at type definitions:1
    frame #1: 0x000000010cc32f1b jetski.dylib`psv_write_outputs(fd=13, buffer=0x0000000101d83000, buffer_end=0x0000000101dc2fff, buffer_ptr_ptr=0x00007fff5fbfb770, entity=0x0000000102883000, entity_size=4, fleet=0x0000000101f0db00) + 747 at write all outputs:52
``

**Comment by amosr** [comment]
did you fix this, @tranma ?

**Comment by tranma** [comment]
@amosr pretty sure I did. Passed 100000 tests without segfault, might as well be labelled "verified compiler"!
