### ISSUE TITLE
Leftover TODO from New Core

### ISSUE THREAD

**Issue by amosr** [ambiata/icicle#303]
TODO:

1. ~~isStreamWindowed in Stream/Stream~~
2. ~~condenseStreams in Program/Condense~~
3. tracking bubblegum in Core evaluator
4. ~~Distinct could be simplified to store (Map key ()) of whether given key has been seen and update accumulator in-place~~
5. Core->Avalanche conversion ignores KeepFactInHistory/bubblegum and windows
6. Core->Avalanche does not allow fold initialisers to refer to previous fold initialisers but should
...
9. actually implement scan

**Comment by tranma** [comment]
I could help with something easy like (4)?

**Comment by amosr** [comment]
4 would be good, 2 is probably most important, and for scan I think we'll need something that "pulls out" the pre- and postcomputations. need to think about this still

**Comment by amosr** [comment]
I have done 2. the other things are relatively low priority for now, I think

**Comment by amosr** [comment]
I ended up doing 4 because it was the easiest way to thread the fact ids into latest for distincts

**Comment by amosr** [comment]
scan still isn't implemented, but the rest is. see #216.
