### ISSUE TITLE
`keys`, `values` map primitives

### ISSUE THREAD

**Issue by tranma** [ambiata/icicle#314]
We should add `keys` and `values` primitives to map, which just gives the keys and values. This should be free as they are already in memory, and in the case of the C backend, already in a handy array by themselves.

Motivation: need it to implement this Ivory expression: `mackerel:unique_catches|window=2 months|expression=union|source=mackerel:days_catch`, which gives all the unique catches

**Comment by amosr** [comment]
sounds good to me. only caveat is that, as they currently are, keys will not be ordered

**Comment by amosr** [comment]
is this done?

**Comment by tranma** [comment]
yup
