### ISSUE TITLE
PrimOps revamp

### ISSUE THREAD

**Issue by tranma** [ambiata/icicle#321]
Primitives need a bit of clean-up. Currently we have:

  * minimal primitives: binary/unary operators, casting, logical operators, date primitives, constructors for built-in types, projections
  * core primitives: fold, map, latest, window
  * flat avalanche primitives:  things that directly converts to some C function

we should pull out a PrimOps type consisting of operators and functions usable in Source, but implemented in C. We need more map and array primitives in particular, to implement some Ivory queries such as `days_in`, `quantile`.

@amosr @jystic

**Comment by amosr** [comment]
:+1:

**Comment by tranma** [comment]
First thing to do is remove the ambiguous double -> int cast and replace with primitive (but non-savage) floor/ceiling/truncate. Needs to be done before it's used to produce models.

**Comment by amosr** [comment]
ok, for now you can put your versions in the Prelude though can't you?

**Comment by amosr** [comment]
I think this might be done, too?

**Comment by tranma** [comment]
done-ish I guess? We have rejigged the common primitives a bit since this issue.
