### ISSUE TITLE
Integrating with Ivory

### ISSUE THREAD

**Issue by tranma** [ambiata/icicle#323]
- Outputting dense PSV . This should be easier than providing a pivotting tool. We can just use the tombstone from the dictionary, e.g. `Entity|Val1|NA|Time1`
- (Maybe) read sequence and thrift files in Ice? (Depends). @jystic said this is his favourite thing.

@amosr

**Comment by markhibberd** [comment]
> We can just use the tombstone from the dictionary,

@tranma Not quite, output isn't a tombstone it is a "missing value", and it needs to be the same for all features where the tombstone is potentially different per fact. Generally how we handle this one is default to "NA" and have a flag that overwrites what it uses for all features.

**Comment by tranma** [comment]
@markhibberd ah, cool. One silly question though, why does this special "missing value" (output tombstone?) need to be the same for all features?

**Comment by jystic** [comment]
@markhibberd so we need a new thing in the dictionary?

**Comment by markhibberd** [comment]
@jystic Normally we don't put in dictionary, it is an artefact of the output format not of the feature/dictionary.

@tranma It doesn't have to be I guess, but it is a convention we have always followed strongly. Allowing different ones makes consumption of the output significantly more difficult for no real advantage. The reason for allowing different tombstones on input has been to handle that facts come from lots of different sources all with their own convention. We just don't want to add to that problem, so have always normalised.

**Comment by jystic** [comment]
@markhibberd ok, so it would be an argument to ice, defaulting to NA?

**Comment by markhibberd** [comment]
@jystic Yeh, I think that is enough.

**Comment by amosr** [comment]
I think the other large thing we'll have to do is output the bubblegum somehow.
for Ivory, we need to restrict to only windowed and latest queries, and I suppose the C code will emit the list of all facts that are used (to a separate file?)

**Comment by amosr** [comment]
whoops

**Comment by amosr** [comment]
good enough
