### ISSUE TITLE
Can't build on GHC 7.10.1 due to dates package

### ISSUE THREAD

**Issue by jystic** [ambiata/icicle#35]
The `dates` package depends on `syb-0.3.x` but the `syb` authors haven't uploaded a `0.3.x` series package which supports `base-4.8` just yet.

`syb-0.4.x` and `syb-0.5.x` both support `base-4.8` already.

**Comment by amosr** [comment]
ack. I'll see if I can rip it out and replace it without too much effort. otherwise you might be out of luck ;-)

**Comment by tranma** [comment]
we should probably replace syb with the lens plated. I don't want a massive dependency on lens either but that seems to be the way people want to move forward.

**Comment by amosr** [comment]
I didn't really expect a date library would be doing that much boilerplate anyway

**Comment by tranma** [comment]
I misread this as icicle itself using syb..... plz disregard.

**Comment by amosr** [comment]
old hat
