### ISSUE TITLE
Not all array updates can be mutable

### ISSUE THREAD

**Issue by amosr** [ambiata/icicle#364]
At the moment, array and map updates in the generated C code mutate the array in-place. This is fine for all the existing code, as users can only add arrays and maps in carefully chosen ways.
However, this will cause issues when we allow arbitrary arrays and maps in Icicle queries.

1. Add C array functions that copy-and-update
2. Add Flat primitives for both mutating and pure
3. Flattening should map to the Pure primitives
4. Implement some sort of 'mutation recovery' transform

Mutation recovery:

```
read arr = acc$arr
let arr' = copyUpdate# arr ix val
write acc$arr = arr'

===========>

read arr = acc$arr
let arr' = mutateUpdate# arr ix val
write acc$arr = arr'
```
(those are probably bad names for the primops)

However this is only possible if "arr" is not referred to after the copyUpdate. Also, any other scalars the accumulator is read into previously must be taken into account.

Here are some examples which cannot be 'recovered':

1. A simple example where the originally read "x" is referred to after the update
```
read x = array
let x' = copyUpdate#  x ix val
write array = x'

let oldval = index# x ix
```

2. If we read the same array into another accumulator before, any read from the first accumulator also stops mutation
```
read FIRSTREAD = array

read x = array
let x' = copyUpdate#  x ix val
write array = x'

let oldval = index# FIRSTREAD ix
```

3. It gets a bit harder when there are loops (and ifs and control flow in general I guess): while "oldval" is not syntactically or structurally "after" the copyUpdate# in this example, it is "after" in the sense that a trace would execute oldval after.
```
read FIRSTREAD = array

for facts
{
  read x = array
  let x' = copyUpdate#  x ix val
  write array = x'
}
let oldval = index# FIRSTREAD ix
```

4. This can even happen at the start of loops...
```
read FIRSTREAD = array

for facts
{
  let oldval = index# FIRSTREAD ix

  read x = array
  let x' = copyUpdate#  x ix val
  write array = x'
}
```

**Comment by amosr** [comment]
@tranma

**Comment by amosr** [comment]
I think the ideal place to put this transform is after flattening, but *before* melting. Melting shouldn't affect whether "mutation" can be "recovered", but would potentially add more array updates that need to be checked.

**Comment by tranma** [comment]
done here https://github.com/ambiata/icicle/pull/377

now we can do things like bake in user maps, arrays, etc.
