### ISSUE TITLE
Builtin "now" should not be an Aggregate

### ISSUE THREAD

**Issue by tranma** [ambiata/icicle#371]
`now` should be `Pure` rather than `Aggregate` in non-bigdata mode. In bigdata mode, it should still be `Aggregate` to make sure folds don't mention it.

**Comment by amosr** [comment]
actually, even in bigdata mode it can be Pure - because bigdata requires them all to be under windows or latests.

I would still like an option for it (just add it to CheckOptions or whatever) but it doesn't have to be exposed in the repl or anything yet.
