### ISSUE TITLE
Icicle-bench is slower than Icicle-repl.

### ISSUE THREAD

**Issue by amosr** [ambiata/icicle#374]
To do the same dictionary with only one query, icicle-bench takes significantly longer than icicle-repl on the same query. Ice suffers the same fate as icicle-bench.

Icicle-bench does do a tiny bit more work by generating PSV parsing code etc, but it shouldn't be that much. There is something wrong.

Profiling icicle-bench claims that Fresh bind >>= is taking the majority of the time and allocation, but this is dubious at best. I tried playing with profiling options, as well as INLINE and NOINLINE on Fresh, and no real difference. I also tried optimising Fresh by converting it to unsafePerformIO and all sorts of other junk, but no difference.

One of the profiles did suggest "substXinS" being a high one. Substitution could definitely be improved by doing multiple substitutions at the same time (taking a Map instead). However, this doesn't really explain why icicle-bench is slower than icicle-repl.

This is relatively low priority for now: while slow compilations are annoying for Ice, they will be much less of an issue for Icicle (because the actual computation will take a hours rather than minutes).

**Comment by amosr** [comment]
I think this is "fixed" now, right @tranma ?

**Comment by tranma** [comment]
no, I don't know if ice/icicle-bench is still slower than icicle-repl

**Comment by amosr** [comment]
0h, yeah, I was getting confused

**Comment by amosr** [comment]
no longer exists
