### ISSUE TITLE
Discuss splitting into multiple modules.

### ISSUE THREAD

**Issue by markhibberd** [ambiata/icicle#424]
It would be nice to split out source level parsing / type-checking without some of the dependencies on c/code-gen. Case I need is embedding it in an upstream service where I want to be able to parse, typecheck, validate and pretty print for online editing of expressions. Not sure how possible this is or how much impact it would have, but it would make a big difference to dev'ing other projects.

**Comment by markhibberd** [comment]
@jystic @tranma @amosr

**Comment by tranma** [comment]
This shouldn't be too bad, splitting into something like: `icicle-source`, `icicle-core`, `icicle-avalanche`, `icicle-sea` (DDC style) sounds good to me.

**Comment by amosr** [comment]
it sounds relatively straightforward.
if we rename `Source.ToCore.*` into `Core.FromSource`, we should be able to split out to a few projects: `icicle-common` (`Icicle.Common.*`, `Icicle.Data.*`), `icicle-source` (`Icicle.Source.*`, `Icicle.Storage.*`) and `icicle-meat` (everything else, could be divided further).

then your case would just rely on `icicle-common` and `icicle-source`, and I think the dependencies for that would end up as something like this. is `jetski` your main concern?
```
                       base
                     , ambiata-p
                     , ambiata-x-eithert
                     , annotated-wl-pprint
                     , bifunctors
                     , containers 
                     , dates -- not sure about this one
                     , deepseq
                     , hashable
                     , lens -- damn
                     , scientific
                     , text -- probably, not certain
                     , thyme
                     , time -- not sure
                     , time-locale-compat -- not sure
                     , transformers
                     , unordered-containers
                     , validation -- hmm
                     , vector
                     , vector-space -- used one place
                     , parsec
```

**Comment by amosr** [comment]
actually maybe it's better off leaving it as-is and not moving `Source.ToCore`, since the core language shouldn't really rely on the source language should it?

**Comment by tranma** [comment]
- while we are at it, splitting out the TOML stuff into a separate package would eliminate many of those questionable dependencies from the other packages.
- I think it makes sense for "downstream" languages to have a dependency on higher level ones.

**Comment by amosr** [comment]
ok, so talking to jacob, we agreed to leave `Icicle.Source.ToCore` where it was, and have `icicle-source` depend on `icicle-core` rather than the other way around

**Comment by amosr** [comment]
I believe this is done
