### ISSUE TITLE
Use anemone for memory pool

### ISSUE THREAD

**Issue by jystic** [ambiata/icicle#489]
Need this before the next snapshot

**Comment by tranma** [comment]
this should happen at the same time as switching to keeping track of alloc'd memory per entity?

**Comment by tranma** [comment]
you mean anemone should keep track of allocation?

**Comment by amosr** [comment]
yup. I was planning on overestimating - counting total number of blocks allocated rather than actual used bits. which means it should only be at most 1MB larger than it really is

**Comment by amosr** [comment]
ie keep total size of allocated blocks in top-level `mempool` struct, so fast case allocs are still fast, when it runs out of a block it adds that to the total on mempool since it has to touch it then anyway

**Comment by jystic** [comment]
Worth noting that this will break icicle-make (pulling in anemone in generated code), but I don't think that's a priority for the moment.
