### ISSUE TITLE
Java generation ignores exceptions

### ISSUE THREAD

**Issue by amosr** [ambiata/icicle#54]
Conversion to Java just outputs a simple division, but we need catches around divisions and so on.
We also need to keep track of whether a particular value is an exception - throwing exceptions is too coarse when we are computing multiple virtual features at once.

So, for example, if we were computing
```
feature salary ~> (sum value / count), (filter value > 0 ~> sum value / count)
```
if the input data were purely negative, we should end up with an average on the left, but an error on the right.
This means the return type is actually something like ``(Maybe Int, Maybe Int)``.

**Comment by amosr** [comment]
In this case the division is outside the loop, so boxing up the Maybe Int (probably just Integer in java) is not a big deal.
In general, for exceptions inside the loop, we should probably represent potentially-exceptional values as pairs of variables with (boolean, int) to avoid allocations. Make it so

**Comment by charleso** [comment]
![make it so](https://thabto.files.wordpress.com/2013/10/make-it-so-captain.jpg)

**Comment by amosr** [comment]
Division no longer throws "exceptions" (bottoms), but since we will be treating tombstones the same way, this is still an issue.

Conversion to Core was too complicated when I tried explicitly passing around exceptional values as maybes/eithers in Core.
I see three options:

1. A separate Source -> Source transform that makes the exceptional things like Possiblies explicit. This would basically turn an "Possibly t" into an "Either err t", and any function applications would unwrap the either etc.

2. Thread the Possibly modality all the way through to Core and Avalanche. This way the core expressions would have types like "Possibly Int" and function application would work as in Source - that is, if you have a function "Int -> Double" and you apply a "Possibly Int", the result is "Possibly Double".

3. In code generation, or some Avalanche transform, assume everything can be an exception, converting *every* variable to Either err t. We could probably code gen that as two variables, an optional error and the actual value. We would then rely on later optimisations to remove the superfluous ones.

I think (1) is probably the best. We keep a simple Core language, the Source->Core conversion doesn't become any more complicated.

**Comment by amosr** [comment]
The "exceptions" are more like bottoms than anything else. I guess maybe this is a lazy language after all.

**Comment by amosr** [comment]
this is fixed with the ReifyPossibility transform.
