### ISSUE TITLE
PrimArithPow on ints

### ISSUE THREAD

**Issue by amosr** [ambiata/icicle#580]
We have a `PrimArithPow` primitive, which works for Ints and Doubles. Two problems:

1. We don't have a C implementation of `iint_pow`
2. Evaluator for ints uses `(^)` which barfs on negative exponents.

We could remove integer pow, since presumably nobody's using it, or we could make it return 0 on negative.
We could also make it return Possibly, but that's a bit more effort, since it'd require a specialised prim to check for negatives or something. (It wouldn't just fall out from the Double Possibly stuff)

**Comment by jystic** [comment]
I'd be in favour of only supporting it for doubles

**Comment by amosr** [comment]
#621 #622
