### ISSUE TITLE
Known issues

### ISSUE THREAD

**Issue by tranma** [ambiata/icicle#602]
These are test failures that are known to occur occasionally. They will be fixed eventually. (Could you be the one?!)

- `prop_success_array_of_struct_input`: `unsafeSubstExp` https://github.com/ambiata/icicle/issues/599
- `prop_success_array_of_struct_input`: `glibc detected: corrupted chunks`

**Comment by tranma** [comment]
these should be gone forever when PSV is removed.

**Comment by amosr** [comment]
OK if I close this, now that PSV is gone?
