### ISSUE TITLE
Beta reduction should simplify lets the same as lambdas

### ISSUE THREAD

**Issue by jystic** [ambiata/icicle#606]
```
let x = y in x
==>
y
```

**Comment by tranma** [comment]
not sure why we only do it when `y` is a value (https://github.com/ambiata/icicle/blob/master/icicle-data/src/Icicle/Common/Exp/Simp/Beta.hs#L38), gotta discuss with the big boss

**Comment by amosr** [comment]
Yeah, so variable should be fine, but anything else you might duplicate work. `isSimpleValue` (https://github.com/ambiata/icicle/blob/master/icicle-data/src/Icicle/Common/Exp/Simp/Beta.hs#L77) is really "is simple or value" rather than simple and value.
So maybe betaToLets should just substitute simple/values in.

Is this really a problem though?

**Comment by jystic** [comment]
It was just to improve the core output so it's easy to read.

**Comment by amosr** [comment]
Oh ok, cool

**Comment by amosr** [comment]
So is `y` a variable in this case, or an expression? For general expressions we'd want something like free variables `freevars' :: Exp n -> Map n Count` to see if it's used multiple times.
We might be able to get away with just matching on `XLet x y (XVar x)` though?

**Comment by jystic** [comment]
`y` is an expression and a pretty decent one at that, that's why it would be nice to reduce.

Yeah matching on `XLet x y (XVar x)` sounds like it would work I think.

**Comment by tranma** [comment]
@amos yeah I'm ok with matching on `XLet x y (XVar x)` (the conversion even has a name, so it's legit!)

**Comment by amosr** [comment]
Is that a specialised form of "zeta", or does it have its own name?

**Comment by amosr** [comment]
I think zeta is more general `let x = e in e' --> e'[x := e]` but I don't know. in a CBV semantics you would restrict the binding to a value, but I guess that would work in CBN?
