### ISSUE TITLE
Flattening/desugaring for source case expressions

### ISSUE THREAD

**Issue by amosr** [ambiata/icicle#78]
Case expressions with nested constructors need to be desugared before conversion to Core.
Or, the Core conversion needs to be improved to deal with nested constructors, but I think desugaring is the simpler option.

For example, this case expression with nested constructors cannot be converted as-is:
```
     case x
      | Some (Some v, None) -> v
      | Some (None, Some v) -> v
      | _                   -> 0
     end
```

We need to pull out the nested constructors to separate cases.
Because we don't have local function definitions, it is easier to just duplicate the alternative code for each new alternative.
We might end up with the same expression duplicated a few times, but it's not a big problem for such small queries (and it's possible we might get some specialisation gains from it)

So here, the x first needs to be changed to a case on the outer part of x: just whether it's Some or None.
In the None case, the default -> 0 applies. In the Some case, we need to check if the inner bit is (Some v, None) or (None, Some v). If it's neither, the default of the outermost case applies (0).

```
     case x
     | Some y
     -> case y
        | (l,r)
        -> case l
           | Some v
           -> case r
              | Some _
              -> 0
              | None
              -> v
              end
           | None
           -> case r
              | Some v
              -> v
              | None
              -> 0
              end
           end
        end
     | None
     -> 0
```

To implement this, you'll probably need a fresh name supply, so the type would be something like
```
desugarQ :: Query a n -> Fresh n (Query a n)
```
and it's probably worth adding as a module Icicle.Source.Transform.Desugar or something.

but it might end up that you need the type of the scrutinee as well (but unlikely the type of the alternatives), so you might need:
```
desugarQ :: Query (Annot a n) n -> Fresh n (Query (Annot a n) n)
```

The Core conversion does not handle nested constructors, nor default patterns or variable patterns at the top level.
We need to remove default and variable patterns and duplicate the alternative for each actual constructors - or in the special (useless) case of just one alternative: 
```
case x 
 | _ -> do stuff with x
end
```
we can probably remove the case altogether:
```
do stuff with x
```

After this is implemented, should be able to add more interesting patterns to the Arbitrary in test/Icicle/Test/Source/Arbitrary.hs, line 47.

It will also be useful to look at src/Icicle/Source/ToCore/Exp.hs (convertCase)

**Comment by amosr** [comment]
Actually, if we can do this *before* type checking, it will make exhaustive checks trivial

**Comment by tranma** [comment]
Shall I attempt this? We need it for a new fancy `sd` function for prelude.icicle.

**Comment by amosr** [comment]
this would be super awesome.

I also realised that I'm an idiot and the current stuff doesn't work at all except for bools.
The problem is that it doesn't use "convertFreshAdd" for the variables in the patterns.  "convertFreshAdd" maps a source name to a unique core name, more or less.
Probably in ``Icicle/Source/ToCore/Exp.hs`` we want "convertCaseFreshenPat :: Pattern n -> ConvertM a n ()`` that recurses down and freshens any pattern variables.
Then, everywhere that calls convertCase, we need to add a convertCaseFreshenPats call *before* the alternatives are recursed into.

For example in https://github.com/ambiata/icicle/blob/master/src/Icicle/Source/ToCore/ToCore.hs#L593 make sure you freshen the names before the mapping convertReduce over alts.

**Comment by tranma** [comment]
Yeah, I thought some binding-thing must be missing, because when I tried `case acc | (a, b) -> ...`, it didn't  work, but `let a = 0 ~> let b = 0 ~> case acc | (a, b) -> ...` did. I'll "enfreshinate" the names then.

**Comment by amosr** [comment]
power up the enfreshulator

**Comment by amosr** [comment]
Tran fixed this
