### ISSUE TITLE
Possibly modality being ignored in Source typechecker

### ISSUE THREAD

**Issue by amosr** [ambiata/icicle#81]
The Source typechecker (Icicle.Source.Checker.Constraint) should compute Possibilities; Possibly or Definitely.

Possibility is a bit simpler than Temporality, because Possibility is a full lattice (right?): there is always a meet and a join; Possibly U Definitely = Possibly and so on.
(Whereas Temporality is not; Element U Aggregate = {} or something)

Anyway, we need a new constraint for getting the upper bound of two possibilities. Something like
```
PossibilitiesUpperBound Definitely d = d
PossibilitiesUpperBound Possibly _ = Possibly
PossibilitiesUpperBound p q = PossibilitiesUpperBound q p
```
This can be added to Icicle.Source.Type.Constraints.

Now, the return possibility of most things will be the upper bound of all its arguments. Look at filter, for example
```
filter Definitely ~> Definitely   : Definitely
filter Possibly ~> Definitely   : Possibly
filter Definitely ~> Possibly   : Possibly

filter x ~> c : PossibilitiesUpperBound x c
```
This is quite different from temporality, where filter requires its expression to be Element and the return to be Aggregate.

For function application the idea is the same as for temporality.
If the expected (function type) and the actual (argument type) possibility are the same, function application is as normal.
If the expected and actual are different, either:
1. Expect Definitely, actual Possibly: the function must be modified to return a Possibly. Think of this as unboxing the argument, then reboxing the result of function application.
2. Expect Possibly, actual Definitely: application as normal

For Case expressions, any variables you bind in a pattern have the same possibility and temporality as the scrutinee.
For example, if you have
```
case (xs : Element Possibly (List Int))
 | Cons one rest -> …
```
here, ``one`` and ``rest`` are also ``Element Possibly``.
The return possibility is the upper bound of the scrutinee and all the alternatives.

Lets just use the possibility of the "in" body. It is much simpler than temporality for lets.

Primitives can just be Definitely, because any Definitely can be converted to a Possibly. It is basically pure. Note that in Icicle.Source.Checker.Prim, the primitives are just bare, unmoded types. This is fine because "canonT" and "decomposeT" which are used to check the modes in Checker.Constraint will convert them to Definitely.

**Comment by tranma** [comment]
bit late to ask.... but what exactly is `Possibility` modality? I'm running into this in the source type checker and I'm getting unification variables in the result type for this modality thing.

**Comment by amosr** [comment]
oh... it's like an (Either error) monad. well, ``Possibly = Either error``, ``Definitely = Identity``.
what do you mean, running into it while implementing something other than this? you should, for now, be able to ignore Possibility - or if not ignore it, you can explicitly set types to definitely with
```
definitelyT t = canonT $ Possibility Definitely t
```

**Comment by tranma** [comment]
I mean, during type checking the Source, I might get something like `Aggregate t$5 Int`, where the variable is some "possibility", and wasn't sure how to make it go away.

**Comment by amosr** [comment]
I have fixed this
