### ISSUE TITLE
Case constraints are too strict

### ISSUE THREAD

**Issue by tranma** [ambiata/icicle#89]
When generating constraints for case expressions, Source requires "the scrutinee and the alternatives must have the same temporality". Could this restriction be relaxed? There's a comment that this may be restrictive than necessary....

Example: `let fold1 a = ((0,0),0) : case a | ((n,m),m2) -> (let d = (double value) - m ~> ((n + 1, m + d / n), m2 + d * ((double value) - m))) end ~> ...`

**Comment by amosr** [comment]
ahh. good catch. yep!
so there is a constraint called ``ReturnOfLet`` or something, which computes the return temporality of a let.
maybe we could require all the alternatives to be the same temporality, and then the return temporality will just be ``ReturnOfLet scrut alts``?

**Comment by amosr** [comment]
Tran fixed this
