### ISSUE TITLE
Add flag to ignore .icicle file when running tests

### ISSUE THREAD

**Issue by jystic** [ambiata/icicle#95]

**Comment by tranma** [comment]
or the test script can "mv .iciclce .yolo" then mv back (Agile!)

**Comment by jystic** [comment]
![agile](http://edge.alluremedia.com.au/uploads/businessinsider/2015/09/Malcolm-Turnbull.jpg)

**Comment by tranma** [comment]
might do this soon. So annoying.

**Comment by amosr** [comment]
I don't actually have a .icicle file, but I just run ``dist/build/icicle-repl/icicle-repl ":set +core +annotated" ":import data/libs/prelude.icicle" "feature salary ~> sum value"`` and so on when I'm testing

**Comment by amosr** [comment]
this seems trivial - worth doing

**Comment by amosr** [comment]
I don't actually use a .icicle file, I just pass everything on the command line. do other people?

**Comment by jystic** [comment]
I use it, it's handy 💃 but it would have a lot less friction if we implemented this.

There's more stuff I'd like to be able to configure with the repl too, like custom color schemes. Options might be like `:set +true-color`, `:set color.types 0x007f00` or similar.

**Comment by tranma** [comment]
what's wrong with `mv .icicle foo`?
